In [344]:
#Importing necessary libraries for data manipulation, visualization, and feature scaling.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [345]:
#Reading a csv file and storing it in a DataFrame, header=None means that the csv file doesn't have column names.
df=pd.read_csv('irdata.csv', header=None)

In [350]:
# show the data frame
df

,0,1,2,3,4,5,6,7,8,9,...,4926,4927,4928,4929,4930,4931,4932,4933,4934,4935
0,0.727547,0.436487,0.436237,0.427712,0.436487,0.436296,0.436365,0.436093,0.432883,0.442032,...,1.000000,1.000000,0.716124,0.740675,0.821445,0.277983,0.342729,0.292667,0.298814,135
1,0.627582,0.437165,0.436918,0.428381,0.437165,0.436852,0.436823,0.436284,0.433203,0.442426,...,0.369659,0.369659,0.841689,0.688527,0.773595,0.292954,0.356864,0.346330,0.402266,135
2,0.491325,0.413515,0.413259,0.400100,0.413515,0.413040,0.412783,0.411238,0.406880,0.417392,...,1.000000,1.000000,0.866652,0.886237,0.613836,0.256379,0.316997,0.271693,0.301333,135
3,0.627582,0.396523,0.396262,0.383040,0.396523,0.396019,0.395729,0.394061,0.389289,0.401378,...,1.000000,1.000000,0.841689,0.816964,0.858092,0.215762,0.283666,0.251673,0.324718,135
4,0.727547,0.386050,0.385823,0.381338,0.386050,0.385762,0.385723,0.385065,0.381884,0.388616,...,1.000000,1.000000,0.626536,0.740675,0.657004,0.249940,0.432630,0.308275,0.179608,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,0.831200,0.872691,0.872620,0.869170,0.872691,0.872804,0.872969,0.873105,0.872467,0.874484,...,1.000000,1.000000,0.785998,0.266436,0.267143,0.404525,0.416372,0.333836,0.250655,123
999,0.848678,0.871678,0.871612,0.868207,0.871678,0.871804,0.871963,0.872094,0.871400,0.873146,...,0.429332,0.429332,0.798766,0.226274,0.275550,0.416824,0.464641,0.361588,0.226081,123
1000,0.812621,0.868284,0.868206,0.865800,0.868284,0.868368,0.868489,0.868479,0.867696,0.869487,...,1.000000,1.000000,0.251173,0.257702,0.491838,0.392308,0.388931,0.356607,0.353756,123
1001,0.750370,0.871788,0.871710,0.869361,0.871788,0.871985,0.872127,0.872160,0.871289,0.873276,...,0.005048,0.005048,0.557539,0.350600,0.205783,0.419022,0.357615,0.360969,0.436476,123
1002,0.750370,0.875318,0.875247,0.873700,0.875318,0.875417,0.875555,0.875573,0.874896,0.876166,...,1.000000,1.000000,0.223812,0.524028,0.455369,0.421565,0.407463,0.348212,0.296734,123

In [347]:
#Displaying the information of the DataFrame, such as number of rows, columns, and data types of columns
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Columns: 4936 entries, 0 to 4935
dtypes: float64(4887), int64(49)
memory usage: 37.8 MB
None

In [348]:
#Dropping any columns with missing values from the DataFrame.
df=df.dropna(axis='columns')

In [349]:
df

,0,1,2,3,4,5,6,7,8,9,...,4926,4927,4928,4929,4930,4931,4932,4933,4934,4935
0,0.727547,0.436487,0.436237,0.427712,0.436487,0.436296,0.436365,0.436093,0.432883,0.442032,...,1.000000,1.000000,0.716124,0.740675,0.821445,0.277983,0.342729,0.292667,0.298814,135
1,0.627582,0.437165,0.436918,0.428381,0.437165,0.436852,0.436823,0.436284,0.433203,0.442426,...,0.369659,0.369659,0.841689,0.688527,0.773595,0.292954,0.356864,0.346330,0.402266,135
2,0.491325,0.413515,0.413259,0.400100,0.413515,0.413040,0.412783,0.411238,0.406880,0.417392,...,1.000000,1.000000,0.866652,0.886237,0.613836,0.256379,0.316997,0.271693,0.301333,135
3,0.627582,0.396523,0.396262,0.383040,0.396523,0.396019,0.395729,0.394061,0.389289,0.401378,...,1.000000,1.000000,0.841689,0.816964,0.858092,0.215762,0.283666,0.251673,0.324718,135
4,0.727547,0.386050,0.385823,0.381338,0.386050,0.385762,0.385723,0.385065,0.381884,0.388616,...,1.000000,1.000000,0.626536,0.740675,0.657004,0.249940,0.432630,0.308275,0.179608,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,0.831200,0.872691,0.872620,0.869170,0.872691,0.872804,0.872969,0.873105,0.872467,0.874484,...,1.000000,1.000000,0.785998,0.266436,0.267143,0.404525,0.416372,0.333836,0.250655,123
999,0.848678,0.871678,0.871612,0.868207,0.871678,0.871804,0.871963,0.872094,0.871400,0.873146,...,0.429332,0.429332,0.798766,0.226274,0.275550,0.416824,0.464641,0.361588,0.226081,123
1000,0.812621,0.868284,0.868206,0.865800,0.868284,0.868368,0.868489,0.868479,0.867696,0.869487,...,1.000000,1.000000,0.251173,0.257702,0.491838,0.392308,0.388931,0.356607,0.353756,123
1001,0.750370,0.871788,0.871710,0.869361,0.871788,0.871985,0.872127,0.872160,0.871289,0.873276,...,0.005048,0.005048,0.557539,0.350600,0.205783,0.419022,0.357615,0.360969,0.436476,123
1002,0.750370,0.875318,0.875247,0.873700,0.875318,0.875417,0.875555,0.875573,0.874896,0.876166,...,1.000000,1.000000,0.223812,0.524028,0.455369,0.421565,0.407463,0.348212,0.296734,123

In [259]:
#Displaying the summary statistics of the numerical columns in the DataFrame.
print(df.describe())

              0            1            2            3            4     \
count  1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      0.530386     0.518775     0.518664     0.514915     0.518775
std       0.216792     0.272074     0.272120     0.273084     0.272074
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.333963     0.358848     0.358632     0.352443     0.358848
50%       0.518868     0.500001     0.500001     0.500001     0.500001
75%       0.679126     0.683281     0.683068     0.677174     0.683281
max       1.000000     1.000000     1.000000     1.000000     1.000000

              5            6            7            8            9     ...  \
count  1003.000000  1003.000000  1003.000000  1003.000000  1003.000000  ...
mean      0.518724     0.518782     0.518471     0.516744     0.521193  ...
std       0.272202     0.272302     0.272520     0.272793     0.271856  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       0.358939     0.358998     0.358760     0.355656     0.362521  ...
50%       0.500001     0.500001     0.500001     0.500001     0.500001  ...
75%       0.683235     0.683289     0.683244     0.680337     0.686799  ...
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...

              4926         4927         4928         4929         4930  \
count  1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      0.880275     0.880275     0.499113     0.457606     0.492721
std       0.266026     0.266026     0.231304     0.241467     0.234312
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       1.000000     1.000000     0.305310     0.254228     0.296997
50%       1.000000     1.000000     0.480790     0.426606     0.455369
75%       1.000000     1.000000     0.685540     0.667200     0.686351
max       1.000000     1.000000     1.000000     1.000000     1.000000

              4931         4932         4933         4934         4935
count  1003.000000  1003.000000  1003.000000  1003.000000  1003.000000
mean      0.427666     0.442371     0.453271     0.476099   135.682951
std       0.264624     0.269345     0.261670     0.225870    67.678301
min       0.000000     0.000000     0.000000     0.000000    61.000000
25%       0.199962     0.227309     0.253907     0.310864    92.000000
50%       0.386260     0.381623     0.402809     0.466936   119.000000
75%       0.605077     0.629881     0.641419     0.655932   152.000000
max       1.000000     1.000000     1.000000     1.000000   353.000000

[8 rows x 4936 columns]

In [260]:
#Counting the number of missing values in each column of the DataFrame.
print(df.isnull().sum())

0       0
1       0
2       0
3       0
4       0
       ..
4931    0
4932    0
4933    0
4934    0
4935    0
Length: 4936, dtype: int64

In [261]:
#Checking whether there are any duplicate rows in the DataFrame.
print(df.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
998     False
999     False
1000    False
1001    False
1002    False
Length: 1003, dtype: bool

In [262]:
print(df[df.duplicated()])#there is  no  duplicated rows

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 4936 columns]

In [263]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Columns: 4936 entries, 0 to 4935
dtypes: float64(4887), int64(49)
memory usage: 37.8 MB
None

In [264]:
#Filtering the rows of the dataframe where last column's value is less than 300.
df=df[df.iloc[:,-1]<300]
# drop all outliner data here 300 and above  labeled data is outliner because of that all of the rest is bellow 170

In [338]:
def drop_outliers_MAD(df, columns=None, threshold=20):
    """
    Drops the outlier rows from a DataFrame using the MAD method
    
    Parameters:
    - df: DataFrame to remove outliers from
    - columns: List of columns to check for outliers (default: None, checks all columns)
    - threshold: threshold multiplier for MAD (default: 3.5)
    
    Returns:
    - DataFrame with outliers removed
    """
    if columns is None:
        columns = df.columns
    for col in columns:
        median = df[col].median()
        mad = df[col].mad()
        lower_bound = median - (threshold * mad)
        upper_bound = median + (threshold * mad)
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    return df

In [ ]:
#Removing the outliers from the DataFrame using the MAD method 
#by passing the dataframe to the function 'drop_outliers_MAD'
dd=drop_outliers_MAD(df)

In [375]:
dd

,0,1,2,3,4,5,6,7,8,9,...,4926,4927,4928,4929,4930,4931,4932,4933,4934,4935
0,0.727547,0.436487,0.436237,0.427712,0.436487,0.436296,0.436365,0.436093,0.432883,0.442032,...,1.000000,1.000000,0.716124,0.740675,0.821445,0.277983,0.342729,0.292667,0.298814,135
1,0.627582,0.437165,0.436918,0.428381,0.437165,0.436852,0.436823,0.436284,0.433203,0.442426,...,0.369659,0.369659,0.841689,0.688527,0.773595,0.292954,0.356864,0.346330,0.402266,135
2,0.491325,0.413515,0.413259,0.400100,0.413515,0.413040,0.412783,0.411238,0.406880,0.417392,...,1.000000,1.000000,0.866652,0.886237,0.613836,0.256379,0.316997,0.271693,0.301333,135
3,0.627582,0.396523,0.396262,0.383040,0.396523,0.396019,0.395729,0.394061,0.389289,0.401378,...,1.000000,1.000000,0.841689,0.816964,0.858092,0.215762,0.283666,0.251673,0.324718,135
5,0.573807,0.380026,0.379745,0.372470,0.380026,0.380035,0.380227,0.379414,0.376674,0.385590,...,0.356627,0.356627,0.814416,0.660715,0.658112,0.213033,0.176192,0.187927,0.433808,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0.792944,0.871408,0.871327,0.868100,0.871408,0.871545,0.871670,0.871614,0.870575,0.872960,...,1.000000,1.000000,0.509714,0.453368,0.618142,0.386260,0.343704,0.332040,0.395655,123
997,0.831200,0.871297,0.871221,0.867830,0.871297,0.871342,0.871415,0.871303,0.870296,0.872892,...,0.423763,0.423763,0.301470,0.393906,0.798320,0.378697,0.381890,0.340089,0.329777,123
998,0.831200,0.872691,0.872620,0.869170,0.872691,0.872804,0.872969,0.873105,0.872467,0.874484,...,1.000000,1.000000,0.785998,0.266436,0.267143,0.404525,0.416372,0.333836,0.250655,123
1000,0.812621,0.868284,0.868206,0.865800,0.868284,0.868368,0.868489,0.868479,0.867696,0.869487,...,1.000000,1.000000,0.251173,0.257702,0.491838,0.392308,0.388931,0.356607,0.353756,123
1001,0.750370,0.871788,0.871710,0.869361,0.871788,0.871985,0.872127,0.872160,0.871289,0.873276,...,0.005048,0.005048,0.557539,0.350600,0.205783,0.419022,0.357615,0.360969,0.436476,123

In [265]:
from sklearn.linear_model import LassoCV
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import Lasso




def select_best_features(X, y, threshold=0.01):
    """
    Select the best performing features using Lasso regularization
    
    Parameters:
    - X: Independent variables in the dataset
    - y: Dependent variable in the dataset
    - threshold: Minimum feature importance for selection (default: 0.01)
    
    Returns:
    - X_new: Selected features
    """
    
    # initialize the model
    reg = Lasso(alpha=0.001,random_state=1,max_iter=10000)
    
    sfm = SelectFromModel(reg, threshold=threshold)
    sfm.fit(X, y)
    X_new = sfm.transform(X)
    return X_new

In [ ]:
#Extracting the independent and dependent variables from the DataFrame, 
#'X' for independent and 'y' for dependent
#Selecting the best features from independent variable 'X' using the function 
#'select_best_features' and storing the result in 'xnew'
X=dd.iloc[:,:-1].values
y=dd.iloc[:,-1].values
xnew=select_best_features(X, y)
# xnew now contain only good performance features depend on the Lasso regressor

In [285]:
xnew.shape #checking the shape of the new feature matrix after feature selection.

(603, 662)

In [296]:
#Normalizing the feature matrix X and target variable y using the StandardScaler class from sklearn library.
sc = StandardScaler()
X = sc.fit_transform(xnew2)

In [331]:
#Splitting the data into training and testing sets using the train_test_split function from sklearn.model_selection.
from sklearn.model_selection import train_test_split
#X=df.iloc[:,:-1].values
y=dd.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1, stratify=y)

In [332]:
X_train

array([[ 2.04298749,  2.04298749, -2.04299034, ...,  0.1312797 ,
         0.44901092, -0.76212308],
       [ 2.04299299,  2.04299299, -2.04299585, ..., -1.70987383,
         0.44901092,  1.04520832],
       [-0.00328056, -0.00328056,  0.00356024, ...,  0.47523071,
         0.44901092, -0.36996347],
       ...,
       [-0.36699775, -0.36699775,  0.36725084, ..., -0.80279225,
         0.44901092, -0.26024563],
       [-0.96191662, -0.96191662,  0.96196924, ...,  1.14020431,
         0.44901092, -1.08689764],
       [ 0.07701734,  0.07701734, -0.07692284, ...,  1.66135125,
         0.44901092, -0.76212308]])

In [333]:
y_train

array([167, 167,  92,  92,  90, 135, 111, 153, 135, 167, 135, 135,  92,
       108,  81,  81, 123, 156, 123,  67,  67,  92,  92, 123,  81, 152,
       173, 135,  90, 108, 111,  67,  67,  98,  81, 111, 153, 111,  61,
        61,  92,  90,  92,  92, 153, 135, 135, 144,  67, 111,  90, 144,
       156, 153, 144, 153, 156,  92,  92, 108, 121,  92, 167,  92, 167,
       108, 173,  67, 111, 111, 111, 152, 123, 153,  92, 121,  90,  90,
       123, 123,  92, 144, 123,  92, 111,  67,  61, 152, 152,  61, 123,
       156, 167, 108, 135,  98,  81, 121,  92,  98, 173, 135, 167, 111,
        67, 111, 111, 123, 113,  92, 121, 135,  90,  92, 113, 108, 167,
       121,  98, 153, 121,  61, 119, 173, 123, 167, 123,  81,  61, 153,
       135, 156, 156,  90, 108, 123,  81, 121, 113, 123, 111,  61, 113,
       123, 135,  67, 173, 153, 144,  81,  98, 111,  61, 153,  81, 108,
        92, 156, 111, 135, 108, 153, 135,  81,  92, 153, 135,  92,  61,
       156, 111, 123,  92, 167, 152, 156,  61, 152,  81, 156,  67,  81,
       156,  90,  92,  98, 121,  92, 123, 123,  98,  81, 123, 167,  92,
       156, 123, 113, 121,  90, 121, 156, 173, 135, 156, 119, 111, 111,
       153, 123, 121, 152,  67, 135,  61,  98, 135, 119, 113, 135, 156,
        67,  61, 152,  92, 123, 135, 121, 111, 156, 111, 173,  92,  92,
       135, 121, 156,  92, 123,  67,  67,  81, 113,  67, 153, 123, 123,
       111, 135, 123, 173,  67, 123,  98, 152, 108,  81, 135, 121,  81,
        92, 108, 167, 119,  61, 121,  67, 135,  81, 144, 135, 135, 173,
        98, 108, 121, 156,  92,  81, 111,  61, 121, 135, 111, 152, 167,
        67,  92, 167,  67, 111,  81, 167, 173, 135, 156,  67, 123, 144,
       153,  98,  81, 113,  92, 121, 153,  92, 153, 123, 167, 123, 135,
       111, 123, 119, 153, 173, 167,  81, 156, 152, 173,  92,  92,  92,
       121, 144, 123, 111,  92,  67, 123, 152,  81, 156, 121,  67, 135,
       153, 135, 123,  67, 123,  98, 123, 113,  92, 123, 135,  61, 173,
       135, 135,  81, 156, 173, 144, 173, 111,  67, 123, 152,  92, 121,
       121,  98, 108, 111,  67, 173, 123,  61, 153, 121,  98, 121, 113,
       135,  90,  92, 135, 121,  81, 108, 144, 153,  92,  98, 153,  81,
       123, 121, 153, 121,  67,  90, 111, 167,  81, 135, 167, 173,  92,
       156,  98,  92, 167, 111,  67, 135, 123, 173, 167, 152,  67,  98,
        61, 152,  90, 135, 121, 152, 113,  90, 144, 123, 153, 108, 108,
        92,  92, 173, 156, 152,  67, 167, 173, 167,  90, 113,  61, 111,
       135, 135,  81,  98, 123, 123, 111, 156, 108, 111, 123, 135, 156,
       119, 108, 173, 152, 113, 123,  67,  92,  81,  67, 123, 113, 153,
        67, 144,  92, 111, 153, 144,  90, 121,  98,  67,  90, 108,  92,
        81], dtype=int64)

In [371]:
#Importing Lasso class for Lasso regression,
#make_regression for generating synthetic data
#r2_score and mean_squared_error for evaluating the model performance

from sklearn.linear_model import Lasso
from sklearn.datasets import make_regression
from sklearn.metrics import r2_score, mean_squared_error


# initialize the model
reg = Lasso(alpha=0.004,random_state=2,max_iter=100000)

# fit the model to the data
reg.fit(X_train, y_train)

# make predictions
y_pred = reg.predict(X_test)



##Calculating the R-squared score and Mean Squared Error (MSE)
#between the predicted and actual values of the target variable for the test set.
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R-squared: ", r2)
print("MSE: ", mse)

R-squared:  0.9541307056561931
MSE:  45.220112715532274

The R-squared value of 0.9541307056561931 means that about 95.4% of the variability in the dependent variable (y) can be explained by the independent variables (X). A value closer to 1 indicates a better fit of the model to the data.

The mean squared error (MSE) value of 45.220112715532274 is a measure of how much the model's predictions deviate from the actual values. It is calculated by taking the average of the squares of the differences between the predicted values and the actual values. A lower MSE indicates a better fit of the model to the data.

So overall, the R-squared and MSE values indicate that the model is able to fit the data quite well, with a relatively low error.

In [372]:
from sklearn.model_selection import cross_val_score
# Perform cross-validation using 10 folds
scores = cross_val_score(reg, X, y, cv=10)

# Print the mean and standard deviation of the cross-validation scores
print("Mean score: ", scores.mean())
print("Standard deviation: ", scores.std())

Mean score:  0.8430867972068855
Standard deviation:  0.15003064831126262

these results indicate that, on average, the model has an R-squared score of 0.84 across different splits of the data, which is a good score. Also, the low standard deviation means that the model's performance is consistent across different splits of the data. Therefore, the model should generalize well to new data.

In [373]:
scores

array([0.93846828, 0.96188892, 0.77302754, 0.74151436, 0.96673862,
       0.97930077, 0.94844905, 0.48435695, 0.89543774, 0.74168573])

In [374]:
#This code is printing the predicted values of the target variable (y_pred) and the actual values 
#of the target variable (y_test) for the test set. 
print("y_pred          y_test")
for i,j in zip(y_pred,y_test):
    print(int(i),"  ",j)

y_pred          y_test
65    67
158    156
121    111
136    135
155    156
114    111
125    135
67    61
123    113
138    135
73    81
87    98
80    81
124    111
160    167
107    111
138    156
147    156
68    67
152    153
119    108
75    81
129    121
159    156
169    173
146    153
93    92
133    135
89    92
84    92
66    67
172    173
82    90
82    81
82    81
68    61
97    98
63    67
163    167
88    90
116    121
136    135
102    108
154    153
98    98
80    81
100    98
49    61
140    135
112    135
143    144
158    153
147    144
159    173
147    153
130    135
70    67
82    61
92    90
131    123
110    111
117    111
113    108
116    111
157    152
109    108
168    167
133    123
174    173
171    173
111    113
103    92
127    123
149    144
166    167
156    153
128    123
63    61
121    111
162    167
110    108
105    92
117    113
97    92
102    90
111    121
136    135
127    123
67    67
133    152
171    167
156    156
88    92
127    123
145    152
123    121
110    123
93    92
121    121
95    92
134    121
119    119
95    92
122    123
153    153
152    156
100    92
119    123
124    123
134    135
108    111
115    113
66    67
101    98
77    81
116    123
122    121
98    92
72    67
143    135
149    152

It can be seen that for most of the data points, the predicted values are close to the actual values. However, there are a few data points where the difference between the predicted and actual values is quite high. This means that the model is not able to predict those specific points accurately.

It's important to note that this is based on the specific test set and the specific way the data was split. The performance of the model may be different on other datasets or other ways the data is split. But these results give a good indication of how well the model is performing on the current test set.